language: node_js
node_js:
 - 6

install:
 - yarn install
 - yarn upgrade docx4js

before_deploy:
 - yarn run build

deploy:
 provider: npm
 email: "lalalic@139.com"
 api_key: $NPM_KEY
 on:
  branch: master
